redis:
  enabled: false
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    enabled: false
  image:
    registry: hmctspublic.azurecr.io
    repository: imported/bitnami/redis
  
  global:
    security:
      allowInsecureImages: true


nodejs:
  applicationPort: 3000
  cpuRequests: 250m
  cpuLimits: 2000m
  memoryRequests: 512Mi
  memoryLimits: 2048Mi
  autoscaling:        # Default is false
    enabled: false
    minReplicas: 2
    maxReplicas: 8    # Required setting
    targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization
  environment:
    REFORM_TEAM: rpx
    REFORM_SERVICE_NAME: xui-mo-webapp
    NODE_ENV: production
    UV_THREADPOOL_SIZE: 64
    PUI_ENV: prod
    NODE_TLS_REJECT_UNAUTHORIZED: 1
    MO_HTTP_PROXY: http://172.16.0.7:8080
    MO_NO_PROXY: localhost
    PORT: 3000
    NOW: false
    IDAM_CLIENT: xuimowebapp
    OAUTH_CALLBACK_URL: /oauth2/callback
    MAX_LOG_LINE: 80
    EXCEPTION_OPTIONS_MAX_LINES: 1
    INDEX_URL: /
    LOGGING: debug
    PROTOCOL: https
    SECURE_COOKIE: false
    COOKIE_TOKEN: __auth__
    COOKIE_USER_ID: __userid__
    MICROSERVICE: xui_webapp
    NODE_CONFIG_ENV: prod
    # Allow config mutations is required for Secrets to attach to config object within code
    ALLOW_CONFIG_MUTATIONS: 1
    # Feature Toggles
    FEATURE_APP_INSIGHTS_ENABLED: true
    FEATURE_SECURE_COOKIE_ENABLED: true
    FEATURE_PROXY_ENABLED: false
    FEATURE_TERMS_AND_CONDITIONS_ENABLED: false
    FEATURE_HELMET_ENABLED: true
    FEATURE_REDIS_ENABLED: true
    FEATURE_OIDC_ENABLED: false

    # Redis
    REDIS_KEY_PREFIX: 'activity:'
    REDIS_TTL: 6000

    # IDAM_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    # S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

    SERVICES_CCD_COMPONENT_API: https://gateway-ccd.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_API_SERVICE: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_WEB_SERVICE: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    RD_PROFESSIONAL_API_SERVICE: http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    S2S_SERVICE: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    FEE_AND_PAY_API: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SERVICES_TERMS_AND_CONDITIONS_API_SERVICE: http://xui-terms-and-conditions-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    MANAGE_CASE_LINK: https://manage-case.{{ .Values.global.environment }}.platform.hmcts.net/cases
    MANAGE_ORG_LINK: https://manage-org.{{ .Values.global.environment }}.platform.hmcts.net
    SERVICES_CCD_DATA_STORE_API: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SERVICES_MCA_PROXY_API: http://aac-manage-case-assignment-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SERVICES_IDAM_ISS_URL: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}2.internal:8443/openam/oauth2/realms/root/realms/hmcts
    SERVICES_ROLE_ASSIGNMENT_API: http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

  keyVaults:
    rpx:
      resourceGroup: rpx
      secrets:
        - mo-s2s-client-secret
        - xui-oauth2-token
        - appinsights-connection-string-mo
        - google-analytics-key
        - name: mo-webapp-redis6-connection-string
          alias: mo-webapp-redis-connection-string
        - launch-darkly-client-id
        - system-user-name
        - system-user-password
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

idam-pr:
  enabled: false
