nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    # deprecate
    # IDAM_URL: https://idam-api.aat.platform.hmcts.net
    # S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    NODE_TLS_REJECT_UNAUTHORIZED: 1
    S2S_SECRET: ${S2S_SECRET}
    IDAM_SECRET: ${IDAM_SECRET}
    # Within values.yaml
    #IDAM_API_SERVICE: https://idam-api.aat.platform.hmcts.net
    #IDAM_WEB_SERVICE: https://idam-web-public.aat.platform.hmcts.net
    #RD_PROFESSIONAL_API_SERVICE: http://rd-professional-api-aat.service.core-compute-aat.internal
    #SERVICES_TERMS_AND_CONDITIONS_API_SERVICE: http://xui-terms-and-conditions-aat.service.core-compute-aat.internal
    #S2S_SERVICE: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    APPINSIGHTS_CONNECTION_STRING: ${APPINSIGHTS_CONNECTION_STRING}
    #FEE_AND_PAY_API: https://payment-api-aat.service.core-compute-aat.internal
    MANAGE_CASE_LINK: https://manage-case.aat.platform.hmcts.net/cases
    MANAGE_ORG_LINK: https://manage-org.aat.platform.hmcts.net/

    PUI_ENV: aat
    LOGGING: debug
