nodejs:
  applicationPort: 3000
  memoryLimits: 1024Mi
  cpuLimits: 1000m
  environment:
    REFORM_TEAM: rpx
    REFORM_SERVICE_NAME: xui-mo-webapp
    NODE_ENV: production
    UV_THREADPOOL_SIZE: 64
    APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
    PUI_ENV: preview
    S2S_SECRET: ${S2S_SECRET}
    IDAM_SECRET: ${IDAM_SECRET}
    SSL_KEY: ${SSL_KEY}
    SSL_CERT: ${SSL_CERT}
  keyVaults:
    rpx:
      resourceGroup: rpx
      secrets:
        - test-email
        - xui-s2s-token
        - xui-oauth2-token
        - fr-email
        - fr-password
        - sscs-email
        - sscs-password
        - AppInsightsInstrumentationKey
        - ssl-key
        - ssl-cert
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
